# Generated by Django 4.2 on 2023-04-25 03:01

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=App.models.upload_to)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
